name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        qpid_user_pass: TERsiXuB
        qpid_admin_pass: 8fM12c09
      with:
        name: diamon/qpid
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: qpid_user_pass,qpid_admin_pass
